### ISSUE TITLE
关于配置的疑问

### ISSUE THREAD

**Issue by helsonxiao** [kiki0805/TodoList-v1#1]
* 没有配置 pg_hb.conf 也能运行（不太清楚怎么配置233，把端口地址加入就好了？）
* 得运行 python manage.py migrate auth => python manage.py migrate => python manage.py createsuperuser ，不然会报错。

我最近也在学习前后端分离做 todolist ，看了你的代码收获很多，感谢博客分享！

**Comment by kiki0805** [comment]
pg_hb.conf应该是对登陆数据库认证方式的一些设置，
[https://www.postgresql.org/docs/current/static/auth-pg-hba-conf.html](https://www.postgresql.org/docs/current/static/auth-pg-hba-conf.html)
我猜我之前数据库认证出错可能是因为默认设置是md5格式的密码，而我传入的是未加密的密码。

另外确实需要先python manage.py migrate auth，我忘记用一个空数据库测试了，多谢提醒！

**Comment by zezhehh** [comment]
pg_hb.conf应该是对登陆数据库认证方式的一些设置，
[https://www.postgresql.org/docs/current/static/auth-pg-hba-conf.html](https://www.postgresql.org/docs/current/static/auth-pg-hba-conf.html)
我猜我之前数据库认证出错可能是因为默认设置是md5格式的密码，而我传入的是未加密的密码。没有配置也能运行....或许你安装的版本默认方法是password，或者之前配置过？

另外确实需要先python manage.py migrate auth，我忘记用一个空数据库测试了，多谢提醒！
